### ISSUE TITLE
SSH format error

### ISSUE THREAD

**Issue by hiepnguyenngoc** [peterpakos/check_perccli#2]
./check_perccli --host 10.10.10.1 --port 22
UNKNOWN - SSH connection error: %d format: a number is required, not str

**Comment by hiepnguyenngoc** [comment]
# ./check_perccli --host 10.10.10.1 --port 22
UNKNOWN - SSH connection error: %d format: a number is required, not str

**Comment by sjbotha** [comment]
Please add --debug to the arguments and post the output.

**Comment by hiepnguyenngoc** [comment]
I enabled debug
```
2019-11-08 18:50:53 [transport] DEBUG Kex agreed: diffie-hellman-group14-sha1
2019-11-08 18:50:53 [transport] DEBUG Cipher agreed: aes128-ctr
2019-11-08 18:50:53 [transport] DEBUG MAC agreed: hmac-sha2-256
2019-11-08 18:50:53 [transport] DEBUG Compression agreed: none
2019-11-08 18:50:53 [transport] DEBUG kex engine KexGroup14 specified hash_algo <built-in function openssl_sha1>
2019-11-08 18:50:53 [transport] DEBUG Switch to new keys ...
2019-11-08 18:50:53 [check_perccli] INFO UNKNOWN - SSH connection error: %d format: a number is required, not str
2019-11-08 18:50:53 [transport] DEBUG EOF in transport thread
```

**Comment by sjbotha** [comment]
It works for me here with those arguments and my IP, login and password.

This error is happening in the SSH library that is trying to make the connection to the server. It looks to me like it is happening when it is trying to parse one of your local ssh files. Most likely it is something with the file ~/.ssh/id_rsa . It might also be ~/.ssh/known_hosts.

One by one try renaming the file away to see which it is.

On mine the output looks like this:
2019-11-08 09:17:27 [transport] DEBUG kex engine KexNistp256 specified hash_algo <built-in function openssl_sha256>
2019-11-08 09:17:27 [transport] DEBUG Switch to new keys ...
2019-11-08 09:17:27 [transport] DEBUG Adding ssh-rsa host key for [192.168.1.4]:22: 06ba1a820387dd4bbbd851d47b475383
2019-11-08 09:17:27 [transport] DEBUG Trying discovered key 2821d603b190d04e24b1efa81c9bf948 in /home/sarel/.ssh/id_rsa
2019-11-08 09:17:27 [transport] DEBUG userauth is OK

**Comment by hiepnguyenngoc** [comment]
I think it is error of variable.

```
# /var/lib/shinken/libexec/check_perccli --help
Traceback (most recent call last):
  File "/var/lib/shinken/libexec/check_perccli", line 47, in <module>
    args = parser.parse_args()
  File "/usr/lib64/python2.7/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1720, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python2.7/argparse.py", line 1926, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python2.7/argparse.py", line 1866, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 1794, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python2.7/argparse.py", line 994, in __call__
    parser.print_help()
  File "/usr/lib64/python2.7/argparse.py", line 2327, in print_help
    self._print_message(self.format_help(), file)
  File "/usr/lib64/python2.7/argparse.py", line 2301, in format_help
    return formatter.format_help()
  File "/usr/lib64/python2.7/argparse.py", line 279, in format_help
    help = self._root_section.format_help()
  File "/usr/lib64/python2.7/argparse.py", line 209, in format_help
    func(*args)
  File "/usr/lib64/python2.7/argparse.py", line 209, in format_help
    func(*args)
  File "/usr/lib64/python2.7/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/usr/lib64/python2.7/argparse.py", line 601, in _expand_help
    return self._get_help_string(action) % params
TypeError: %d format: a number is required, not str
```
